const express = require('express')
const cors = require('cors') 
const app = express()
const connectDatabase = require('./utils.js/connectDatabase')
const routes = require('./routes')
require('dotenv').config() 
//Middlewares 
app.use(cors()) 
app.use(express.json())
app.use(routes)
connectDatabase()
app.listen()