export {default as Home} from './home/Home'
export {default as Shrink } from './shrink/Shrink'
export {default as Upload} from './upload/Upload'
export {default as Deadend} from './deadend/Deadend'
export {default as Contact} from './contact/Contact'